// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    cleaned_records: {
        name: "cleaned_records";
        parameters: {
          /** STRING - use sql.string() */
          run_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          record_id: string;
          /** @sqlType STRING */
          cleaned_record_json: string;
          /** @sqlType BIGINT */
          issue_count: number;
          /** @sqlType BIGINT */
          transformed_count: number;
          /** @sqlType BOOLEAN */
          is_quarantined: boolean;
          /** @sqlType STRING */
          record_status: string;
          /** @sqlType TIMESTAMP */
          cleaned_at: string;
        }>;
      };
    commerce_performance: {
        name: "commerce_performance";
        parameters: {
          /** STRING - use sql.string() */
          run_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          category: string;
          /** @sqlType BIGINT */
          order_count: number;
          /** @sqlType DOUBLE */
          revenue: number;
          /** @sqlType BIGINT */
          delivered_orders: number;
          /** @sqlType DOUBLE */
          revenue_per_order: number;
          /** @sqlType DECIMAL(26,1) */
          delivery_rate_pct: number;
        }>;
      };
    dashboard_kpis: {
        name: "dashboard_kpis";
        parameters: {
          /** STRING - use sql.string() */
          run_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          run_id: string;
          /** @sqlType STRING */
          project_name: string;
          /** @sqlType STRING */
          source_mode: string;
          /** @sqlType STRING */
          source_format: string;
          /** @sqlType STRING */
          source_identifier: string;
          /** @sqlType BIGINT */
          row_count: number;
          /** @sqlType INT */
          column_count: number;
          /** @sqlType BIGINT */
          cell_count: number;
          /** @sqlType BIGINT */
          valid_cells: number;
          /** @sqlType BIGINT */
          issue_cells: number;
          /** @sqlType BIGINT */
          transformed_cells: number;
          /** @sqlType DOUBLE */
          quality_score: number;
          /** @sqlType BIGINT */
          mapped_columns: number;
          /** @sqlType DOUBLE */
          mapping_confidence_pct: number;
          /** @sqlType BIGINT */
          cleaned_rows: number;
          /** @sqlType BIGINT */
          quarantined_rows: number;
          /** @sqlType STRING */
          run_status: string;
          /** @sqlType TIMESTAMP */
          started_at: string;
          /** @sqlType TIMESTAMP */
          updated_at: string;
        }>;
      };
    database_inventory: {
        name: "database_inventory";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          schema_name: string;
          /** @sqlType STRING */
          data_layer: string;
          /** @sqlType BIGINT */
          table_count: number;
          /** @sqlType BIGINT */
          materialized_view_count: number;
          /** @sqlType BIGINT */
          managed_table_count: number;
          /** @sqlType BIGINT */
          column_count: number;
          /** @sqlType STRING */
          assets: string;
        }>;
      };
    quality_by_column: {
        name: "quality_by_column";
        parameters: {
          /** STRING - use sql.string() */
          run_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          column_name: string;
          /** @sqlType STRING */
          source_type: string;
          /** @sqlType BIGINT */
          cell_count: number;
          /** @sqlType BIGINT */
          missing_count: number;
          /** @sqlType BIGINT */
          issue_count: number;
          /** @sqlType BIGINT */
          transformed_count: number;
          /** @sqlType DOUBLE */
          quality_score: number;
          /** @sqlType DECIMAL(26,1) */
          completeness_pct: number;
          /** @sqlType STRING */
          health_status: string;
        }>;
      };
    quality_issue_distribution: {
        name: "quality_issue_distribution";
        parameters: {
          /** STRING - use sql.string() */
          run_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          quality_issue: string;
          /** @sqlType STRING */
          issue_label: string;
          /** @sqlType BIGINT */
          issue_count: number;
          /** @sqlType DECIMAL(26,1) */
          share_pct: number;
          /** @sqlType BOOLEAN */
          is_issue: boolean;
        }>;
      };
    recent_runs: {
        name: "recent_runs";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          run_id: string;
          /** @sqlType STRING */
          project_name: string;
          /** @sqlType STRING */
          source_mode: string;
          /** @sqlType STRING */
          source_format: string;
          /** @sqlType STRING */
          source_identifier: string;
          /** @sqlType BIGINT */
          row_count: number;
          /** @sqlType INT */
          column_count: number;
          /** @sqlType DOUBLE */
          quality_score: number;
          /** @sqlType DOUBLE */
          mapping_confidence_pct: number;
          /** @sqlType BIGINT */
          quarantined_rows: number;
          /** @sqlType STRING */
          run_status: string;
          /** @sqlType TIMESTAMP */
          started_at: string;
          /** @sqlType TIMESTAMP */
          updated_at: string;
        }>;
      };
    schema_mapping: {
        name: "schema_mapping";
        parameters: {
          /** STRING - use sql.string() */
          run_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType INT */
          ordinal: number;
          /** @sqlType STRING */
          source_column: string;
          /** @sqlType STRING */
          target_column: string;
          /** @sqlType STRING */
          source_type: string;
          /** @sqlType STRING */
          target_type: string;
          /** @sqlType DOUBLE */
          confidence_pct: number;
          /** @sqlType STRING */
          name_comparison: string;
          /** @sqlType STRING */
          type_comparison: string;
          /** @sqlType STRING */
          review_status: string;
          /** @sqlType TIMESTAMP */
          profiled_at: string;
        }>;
      };
    source_table_inventory: {
        name: "source_table_inventory";
        parameters: {
          /** STRING - use sql.string() */
          sourceCatalog: SQLStringMarker;
          /** STRING - use sql.string() */
          sourceSchema: SQLStringMarker;
          /** STRING - use sql.string() */
          refreshToken: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          source_system: string;
          /** Schema that contains the relation. */
          database_name: string;
          /** Name of the relation. */
          dataset_name: string;
          /** Catalog that contains the relation. */
          table_catalog: string;
          /** Schema that contains the relation. */
          table_schema: string;
          /** Name of the relation. */
          table_name: string;
          /** Type of the table such as 'MANAGED', 'FOREIGN', 'VIEW', etc. */
          table_type: string;
          /** 'YES' if the relation can be inserted into, 'NO' otherwise. */
          is_insertable_into: string;
          /** @sqlType BIGINT */
          column_count: number;
        }>;
      };
    topology_inventory: {
        name: "topology_inventory";
        parameters: {
          /** STRING - use sql.string() */
          run_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType INT */
          edge_order: number;
          /** @sqlType STRING */
          run_id: string;
          /** @sqlType STRING */
          source_node: string;
          /** @sqlType STRING */
          target_node: string;
          /** @sqlType STRING */
          operation: string;
          /** @sqlType STRING */
          databricks_component: string;
          /** @sqlType STRING */
          governance_state: string;
        }>;
      };
    transformation_summary: {
        name: "transformation_summary";
        parameters: {
          /** STRING - use sql.string() */
          run_id: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          transformation: string;
          /** @sqlType BIGINT */
          evaluated_cells: number;
          /** @sqlType BIGINT */
          changed_cells: number;
          /** @sqlType DECIMAL(26,1) */
          change_rate_pct: number;
          /** @sqlType STRING */
          action_status: string;
        }>;
      };
  }
}
