#!/bin/bash
# ════════════════════════════════════════════════════════════════════
# DataOne - Deploy to Databricks Workspace
# ════════════════════════════════════════════════════════════════════
#
# This script deploys DataOne as a Lakehouse App to a Databricks workspace
# for testing before marketplace submission.
#
# Prerequisites:
#   - Databricks CLI installed and configured
#   - Access to a Databricks workspace with Unity Catalog
#   - Partner Connect access (for app deployment)
#
# Usage:
#   ./deploy.sh [OPTIONS]
#
# Options:
#   -w, --workspace URL      Workspace URL (required)
#   -p, --profile PROFILE    Databricks CLI profile (default: DEFAULT)
#   -n, --app-name NAME      App name (default: dataone-test)
#   -h, --help               Show this help message
#
# Examples:
#   # Deploy to workspace using default profile
#   ./deploy.sh -w https://my-workspace.cloud.databricks.com
#
#   # Deploy with custom profile and app name
#   ./deploy.sh -w https://my-workspace.cloud.databricks.com -p staging -n dataone-dev
#
# ════════════════════════════════════════════════════════════════════

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Defaults
WORKSPACE_URL=""
PROFILE="DEFAULT"
APP_NAME="dataone-test"
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

log() { echo -e "${BLUE}[$(date +'%Y-%m-%d %H:%M:%S')]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1" >&2; }
success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }

show_help() {
    sed -n '2,/^# ═\+$/p' "$0" | sed 's/^# \?//'
}

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -w|--workspace) WORKSPACE_URL="$2"; shift 2 ;;
        -p|--profile) PROFILE="$2"; shift 2 ;;
        -n|--app-name) APP_NAME="$2"; shift 2 ;;
        -h|--help) show_help; exit 0 ;;
        *) error "Unknown option: $1"; show_help; exit 1 ;;
    esac
done

# Validate
if [[ -z "$WORKSPACE_URL" ]]; then
    error "Workspace URL is required. Use -w or --workspace option."
    show_help
    exit 1
fi

# Check Databricks CLI
if ! command -v databricks &> /dev/null; then
    error "Databricks CLI not found. Install it first:"
    echo "  pip install databricks-cli"
    exit 1
fi

log "Starting deployment to Databricks workspace..."
log "Workspace: ${WORKSPACE_URL}"
log "Profile: ${PROFILE}"
log "App Name: ${APP_NAME}"
echo ""

# ════════════════════════════════════════════════════════════════════
# Verify Databricks CLI Configuration
# ════════════════════════════════════════════════════════════════════

log "Verifying Databricks CLI configuration..."

if databricks workspace ls / --profile "$PROFILE" > /dev/null 2>&1; then
    success "CLI configured correctly"
else
    error "Failed to authenticate with Databricks. Check your profile configuration."
    exit 1
fi

echo ""

# ════════════════════════════════════════════════════════════════════
# Upload App Manifest
# ════════════════════════════════════════════════════════════════════

log "Uploading app manifest..."

MANIFEST_PATH="/Workspace/Apps/${APP_NAME}/app.yml"

if databricks workspace import \
    "${PROJECT_ROOT}/databricks/app.yml" \
    "$MANIFEST_PATH" \
    --profile "$PROFILE" \
    --overwrite \
    --format AUTO; then
    success "App manifest uploaded"
else
    error "Failed to upload app manifest"
    exit 1
fi

echo ""

# ════════════════════════════════════════════════════════════════════
# Create App (using Databricks Apps API)
# ════════════════════════════════════════════════════════════════════

log "Creating Lakehouse App..."

warning "Note: This requires Partner Connect access and Apps API preview."
warning "If you don't have access, submit via Databricks Partner Portal instead."

echo ""
echo "Manual deployment steps:"
echo ""
echo "1. Go to: ${WORKSPACE_URL}/apps"
echo "2. Click 'Create App'"
echo "3. Select 'Upload manifest'"
echo "4. Choose: ${MANIFEST_PATH}"
echo "5. Configure OAuth settings:"
echo "   - Client ID: (generated by Databricks)"
echo "   - Client Secret: (generated by Databricks)"
echo "   - Redirect URI: ${WORKSPACE_URL}/apps/<app-id>/api/v1/auth/databricks/callback"
echo "6. Click 'Deploy'"
echo ""

success "Manifest uploaded. Complete deployment via Databricks UI."

echo ""
log "Done!"
